### PR TITLE
Downgrade unleash to iOS v12

### PR DESCRIPTION
**Pull request by pnzr00t**
## About the changes
Downgrade to iOS version 12

Closes #

### CODE REVIEW

**Review by FredrikOseberg — CHANGES_REQUESTED** [review]
Skjermbilde 2023-03-23 kl  13 47 15

Unfortunately it will take more than this to lower the version. The swift SDK currently uses observableObject to propagate changes and its only available in iOS above v13. Making this change would be a breaking change, so I'm not sure if it's worth it at this point. Perhaps forking it and creating a community version resolving the issues could be a way forward?

**Comment by pnzr00t** [comment]
Em yes, but if you see, i'm not made any changes in ObservableObject, its currently inherited from UnleashClientBase, ObservableObject.

image

UnleashClientBase - is class witch you may using in old iOS versions 

image

**Comment by FredrikOseberg** [comment]
> Em yes, but if you see, i'm not made any changes in ObservableObject, its currently inherited from UnleashClientBase, ObservableObject.
> 
> image
> 
> UnleashClientBase - is class witch you may using in old iOS versions. I write example in Readme.md (UnleashClientBase using in 12ios version, UnleashClient in >=13)
> 
> image

Apologies, Swift is not my primary language and I might have jumped the gun on this one. I got these errors while loading the branch into my test iOS test app, I will try again with your suggestions.

**Comment by pnzr00t** [comment]
Great, if you have any problems with my branch, please let me know

**Review by FredrikOseberg — APPROVED** [review]
This looks good. I will merge this and release a beta version.

**Comment by pnzr00t** [comment]
@FredrikOseberg  If you need good ios developer, let me know ;)

**Pull request merged**
