### PR TITLE
Feat/async start and updateContext overloads

### LINKED ISSUE #88: Polling does not work when start called from async context
### Describe the bug

I was trying to wrap calling the start method in modern concurrency so I can call and get completion in async context and I noticed when doing this the poller fails to fire beyond initial fetch. 

### Steps to reproduce the bug

I've included a simple example below where the start is called on the UnleashClient, and upon starting changes some text in a view to say started or failed to start. For this I added:

1. A `startAsync` which wraps the `start` completion in a checkedContinuation to allow it to be called from async (called from `.task` view modifier)
2. A `start` which wraps the included `start` method with a completion block (called form `.onAppear` view modifier)

For both I print out to console ">>> Unleashed!" when it successfully connects. I also have enabled printing status in the client start method.

In both (1) and (2) I successfully see ">>> Unleashed!" print to console showing it did start up. However I only see subsequent client log messages (e.g. `No changes in feature toggles.`) when calling via the onAppear and completion block.

Seeing how the timer is constructed to fire further requests I see it is added to the RunLoop. I'm thinking that is causing an issue when trying to adapt for modern concurrency.

Any thoughts on a fix? (The poller may need a main dispatch queue added)

```swift
import UnleashProxyClientSwift
import SwiftUI

struct ContentView: View {
    @State var text = "Not started"
    
    var body: some View {
        Text(text)
            .task {
                let started = await Unleasher.shared.startAsync()
                if started {
                    self.text = "Started"
                } else {
                    self.text = "Failed to start"
                }
            }
//            .onAppear {
//                Unleasher.shared.start { started in
//                    if started {
//                        self.text = "Started"
//                   } else {
//                        self.text = "Failed to start"
//                    }
//                }
//            }
    }
}

class Unleasher {
    static let shared = Unleasher()
    private let client: UnleashClient
    
    private init() {
        self.client = UnleashClient(
            unleashUrl: "someURL",
            clientKey: "someKey",
            refreshInterval: 3,
            appName: "unleasher-ios-sample"
        )
    }
    
    func startAsync() async -> Bool {
        await withCheckedContinuation { continuation in
            client.start(true) { error in
                if let error {
                    print(error.localizedDescription)
                    continuation.resume(returning: false)
                } else {
                    print(">>> Unleashed!")
                    continuation.resume(returning: true)
                }
            }
        }
    }
    
    func start(completion: @escaping (Bool) -> Void) {
        client.start(true) { error in
            if let error {
                print(error.localizedDescription)
                completion(false)
            } else {
                print(">>> Unleashed!")
                completion(true)
            }
        }
    }
}
```

### Expected behavior

UnleashClient should continue to fetch even when wrapped in methods porting for calling in modern concurrency

### Logs, error output, etc.

_No response_

### Screenshots

_No response_

### Additional context

_No response_

### Unleash version

1.3.0

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

Only noticed in iOS client SDK

### PR DESCRIPTION
**Pull request by benjamin-es-hall**
## About the changes
This adds async overloads for the start and updateContext methods so that they can safely be called from async context in modern swift concurrency. MainActor requirement is needed for the timer within the Poller to fire on the RunLoop.

Fairly sure this should close #88 
Closes #88

### CODE REVIEW

**Review by FredrikOseberg — COMMENTED** [review]
@benjamin-es-hall Thank you! I think it looks sensible, but how will this affect the minimum version of Unleash? In the past we changed away from the usage of ObservableObject on the base in order to support iOS 12. See #34

**Comment by benjamin-es-hall** [comment]
> @benjamin-es-hall Thank you! I think it looks sensible, but how will this affect the minimum version of Unleash? In the past we changed away from the usage of ObservableObject on the base in order to support iOS 12. See #34 

No problem! 

Oh I didn't notice `UnleashClient` was exposed only to iOS13 and that was the differencing factor to `UnleashClientBase`.

In that case, the async methods I've put in `Base` I've marked for only available to iOS13 and shouldn't have any issues, but I think we could equally just move them into `UnleashClient`. Thoughts?

**Comment by benjamin-es-hall** [comment]
@FredrikOseberg just pushed up a commit to move the methods to the UnleashClient class where it already specifies iOS13 requirement

**Comment by FredrikOseberg** [comment]
> > @benjamin-es-hall Thank you! I think it looks sensible, but how will this affect the minimum version of Unleash? In the past we changed away from the usage of ObservableObject on the base in order to support iOS 12. See #34
> 
> No problem!
> 
> Oh I didn't notice `UnleashClient` was exposed only to iOS13 and that was the differencing factor to `UnleashClientBase`.
> 
> In that case, the async methods I've put in `Base` I've marked for only available to iOS13 and shouldn't have any issues, but I think we could equally just move them into `UnleashClient`. Thoughts?
> 
> Would you also be able to explain why ObservableObject is used? It's use case is not clear to me without an example since any changes seem to be propagated via the swiftEventBus and notification center anyway?

Observable object was initially used to allow UI changes to propagate automatically when a feature flag updated. Without it, from my understanding, you'll have to trigger the UI update manually yourself. This was done to keep consistency with how our other client side SDKs handle flag changes.

**Review by FredrikOseberg — APPROVED** [review]
LGTM

**Pull request merged**
